### PR TITLE
Completed Team page

### PR DESCRIPTION
**Pull request by ShivaRapolu01**
Solves #12

### CODE REVIEW

**Comment by ShivaRapolu01** [comment]
@PrateekUp  bhaiya I have added Tilt animation to home page logo also, I will raise a PR for #15 issue once this gets merged. Waiting for this to get merged

**Comment by PrateekUp** [comment]
Send a video of teams page after adding departments once

**Comment by ShivaRapolu01** [comment]
https://www.awesomescreenshot.com/video/6576290?key=6a19b23ca2a770d584d1908dc2740516
@PrateekUp

**Comment by ShivaRapolu01** [comment]
@PrateekUp please update the leaderboard

**Comment by ShivaRapolu01** [comment]
@PrateekUp https://www.awesomescreenshot.com/video/6581897?key=e301faad5640523ccab715a92eda080d . Please have a look at this finished site . 
Don't forget to give extra points if you feel the design and work is good 😆

**Comment by ShivaRapolu01** [comment]
@PrateekUp

**Comment by ShivaRapolu01** [comment]
Please update the leaderboard

**Pull request merged**
