### PR TITLE
Added animations

### PR DESCRIPTION
**Pull request by ShivaRapolu01**
Solves #13 

- [x] corrected 2 web development spelling mistake
- [x] Added fadein animation to the section 1 text 
- [ ] Added  walking-text animation 
image
- [x] Added card-hover animation
image

### CODE REVIEW

**Comment by ShivaRapolu01** [comment]
@PrateekUp  Please have a look at this . I guess this should be treated as easy issue

**Comment by PrateekUp** [comment]
@ShivaRapolu01 send a screen recording. I want to see how animations are working.

**Comment by ShivaRapolu01** [comment]
[Demonstration Video](https://www.awesomescreenshot.com/video/6535352?key=38101ea3807b1d3646785825663f6bb2)

**Comment by ShivaRapolu01** [comment]
Please merge this so that I can start working on #14  Image overflow issue

**Comment by ShivaRapolu01** [comment]
@PrateekUp

**Pull request closed without merging**
